import { useCallback, useEffect, useState } from 'react';
import { Donation, donationApi, DonationStatus } from '../../../services/donationApi';
const statuses: DonationStatus[]=['PENDING','CONTACTED','CONFIRMED','RECEIVED','CANCELLED'];
const labels:Record<DonationStatus,string>={PENDING:'En attente',CONTACTED:'Contacté',CONFIRMED:'Confirmé',RECEIVED:'Reçu',CANCELLED:'Annulé'};
interface Props { onChanged:()=>void; notify:(value:string)=>void; }
export function AdminDonations({onChanged,notify}:Props){const[data,setData]=useState<Donation[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[status,setStatus]=useState(''),[type,setType]=useState(''),[from,setFrom]=useState(''),[page,setPage]=useState(1),[pages,setPages]=useState(0);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await donationApi.admin.list({page,limit:20,status:status as DonationStatus|'' ,type,from});setData(r.data);setPages(r.meta.totalPages)}catch(e){setError(e instanceof Error?e.message:'Chargement impossible')}finally{setLoading(false)}},[page,status,type,from]);useEffect(()=>{void load()},[load]);
 const change=async(id:string,value:DonationStatus)=>{try{await donationApi.admin.status(id,value);notify('Statut du don mis à jour');await load();onChanged()}catch(e){setError(e instanceof Error?e.message:'Mise à jour impossible')}};
 return <AdminList title="Dons" loading={loading} error={error} empty={!data.length} onRefresh={()=>void load()} filters={<><select aria-label="Filtrer par statut" value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}}><option value="">Tous les statuts</option>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select><input placeholder="Type (forage, matériel…)" value={type} onChange={e=>{setPage(1);setType(e.target.value)}}/><input aria-label="À partir de" type="date" value={from} onChange={e=>{setPage(1);setFrom(e.target.value)}}/></>} pagination={<Pagination page={page} pages={pages} setPage={setPage}/>}>{data.map(d=><article key={d.id} className="admin-row"><div><strong>{d.donorName}</strong><p>{d.donorContact}{d.donorEmail?` · ${d.donorEmail}`:''}</p><p>{d.type} · {d.amount!=null?`${d.amount.toLocaleString('fr-FR')} ${d.currency}`:'Don en nature / montant non précisé'}</p>{d.message&&<p className="italic">{d.message}</p>}</div><div><time>{new Date(d.createdAt).toLocaleDateString('fr-FR')}</time><select aria-label={`Statut de ${d.donorName}`} value={d.status} onChange={e=>void change(d.id,e.target.value as DonationStatus)}>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div></article>)}</AdminList>}
export function AdminList({title,loading,error,empty,onRefresh,filters,pagination,children}:{title:string;loading:boolean;error:string;empty:boolean;onRefresh:()=>void;filters:React.ReactNode;pagination:React.ReactNode;children:React.ReactNode}){return <section className="flex flex-col gap-4"><div className="flex justify-between"><h2 className="text-xl font-bold text-[#012d1d]">{title}</h2><button onClick={onRefresh} className="admin-button">Actualiser</button></div><div className="admin-filters">{filters}</div>{error&&<p role="alert" className="admin-error">{error}</p>}{loading?<p className="admin-state">Chargement…</p>:empty?<p className="admin-state">Aucun élément à afficher.</p>:<div className="flex flex-col gap-3">{children}</div>}{pagination}</section>}
export function Pagination({page,pages,setPage}:{page:number;pages:number;setPage:(p:number)=>void}){if(pages<=1)return null;return <div className="flex justify-center items-center gap-3"><button className="admin-button" disabled={page<=1} onClick={()=>setPage(page-1)}>Précédent</button><span className="text-xs">Page {page} / {pages}</span><button className="admin-button" disabled={page>=pages} onClick={()=>setPage(page+1)}>Suivant</button></div>}
