import { useEffect, useState } from 'react';
import { ContentBlock, contentApi, MediaItem } from '../../../services/contentApi';

const labels: Record<string, string> = { 'site.brand': 'Identité du site', 'site.footer': 'Pied de page', 'site.contact': 'Coordonnées', 'site.profile': 'Biographie du Cheick', 'site.guide': 'Guide agricole', 'home.page': 'Accueil', 'agriculture.page': 'Agriculture', 'elevage.page': 'Élevage', 'humanitaire.page': 'Humanitaire' };
const humanize = (value: string) => value.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase());

function Fields({ value, onChange, path = '' }: { value: any; onChange: (value: any) => void; path?: string }) {
  if (Array.isArray(value)) return <div className="flex flex-col gap-3">{value.map((entry, index) => <fieldset key={index} className="border rounded-xl p-3"><legend className="px-2 text-xs font-bold">Élément {index + 1}</legend><Fields value={entry} onChange={(next) => onChange(value.map((item, i) => i === index ? next : item))} path={`${path}.${index}`} /><div className="flex gap-3 mt-2"><button type="button" className="text-xs" disabled={index === 0} onClick={() => onChange(value.map((item, i) => i === index - 1 ? entry : i === index ? value[index - 1] : item))}>Monter</button><button type="button" className="text-xs text-red-700" onClick={() => onChange(value.filter((_, i) => i !== index))}>Retirer</button></div></fieldset>)}<button type="button" className="admin-secondary self-start" onClick={() => onChange([...value, value.length ? Object.fromEntries(Object.keys(value[0]).map((key) => [key, typeof value[0][key] === 'number' ? 0 : typeof value[0][key] === 'boolean' ? true : ''])) : ''])}>Ajouter un élément</button></div>;
  if (value && typeof value === 'object') return <div className="grid md:grid-cols-2 gap-3">{Object.entries(value).filter(([key]) => key !== 'videos').map(([key, entry]) => <div key={key} className={typeof entry === 'object' ? 'md:col-span-2' : ''}><label className="block text-xs font-bold text-[#414844] mb-1">{humanize(key)}</label><Fields value={entry} onChange={(next) => onChange({ ...value, [key]: next })} path={`${path}.${key}`} /></div>)}</div>;
  if (typeof value === 'boolean') return <input type="checkbox" checked={value} onChange={(e) => onChange(e.target.checked)} />;
  if (typeof value === 'number') return <input className="admin-input" type="number" value={value} onChange={(e) => onChange(Number(e.target.value))} />;
  const long = String(value ?? '').length > 90 || /description|biography|quote|text|introduction/i.test(path);
  return long ? <textarea className="admin-input min-h-24" maxLength={12000} value={value ?? ''} onChange={(e) => onChange(e.target.value)} /> : <input className="admin-input" maxLength={2048} value={value ?? ''} onChange={(e) => onChange(e.target.value)} />;
}

const emptyMedia: MediaItem = { slug: '', section: 'home', type: 'reportage', title: '', description: '', body: '', imageUrl: '', imageAlt: '', badge: '', dateLabel: '', metric: '', buttonLabel: '', metadata: {}, order: 0, isActive: true };
export function AdminContent({ notify }: { notify: (message: string) => void }) {
  const [blocks, setBlocks] = useState<ContentBlock[]>([]); const [media, setMedia] = useState<MediaItem[]>([]); const [selected, setSelected] = useState('home.page'); const [draft, setDraft] = useState<any>({}); const [item, setItem] = useState<MediaItem>(emptyMedia); const [busy, setBusy] = useState(false);
  const load = async () => { const payload = await contentApi.admin(); setBlocks(payload.blocks); setMedia(payload.mediaItems); const block = payload.blocks.find((b) => b.key === selected) || payload.blocks[0]; if (block) { setSelected(block.key); setDraft(structuredClone(block.data)); } };
  useEffect(() => { void load().catch((e) => notify(e.message)); }, []);
  const choose = (key: string) => { setSelected(key); const block = blocks.find((b) => b.key === key); if (block) setDraft(structuredClone(block.data)); };
  const save = async () => { setBusy(true); try { await contentApi.update(selected, draft); notify('Contenu publié immédiatement'); await load(); } catch (e) { notify(e instanceof Error ? e.message : 'Échec de sauvegarde'); } finally { setBusy(false); } };
  const editMedia = (entry: MediaItem) => setItem({ ...emptyMedia, ...entry });
  const saveMedia = async () => { setBusy(true); try { item._id ? await contentApi.updateMedia(item._id, item) : await contentApi.createMedia(item); notify('Média enregistré'); setItem(emptyMedia); await load(); } catch (e) { notify(e instanceof Error ? e.message : 'Échec'); } finally { setBusy(false); } };
  return <div className="flex flex-col gap-8"><section className="admin-card"><h2 className="text-xl font-bold mb-1">Contenus du site</h2><p className="text-sm text-gray-600 mb-4">Choisissez une page puis modifiez ses champs. Les changements sont publiés à la sauvegarde.</p><div className="flex gap-2 overflow-x-auto mb-5">{blocks.map((block) => <button key={block.key} onClick={() => choose(block.key)} className={`px-3 py-2 rounded-full text-xs whitespace-nowrap ${selected === block.key ? 'bg-[#012d1d] text-white' : 'bg-gray-100'}`}>{labels[block.key] || block.key}</button>)}</div><Fields value={draft} onChange={setDraft} path={selected} /><div className="flex gap-2 mt-5"><button disabled={busy} onClick={() => void save()} className="admin-primary">{busy ? 'Sauvegarde…' : 'Enregistrer et publier'}</button><button onClick={() => window.open('/', '_blank')} className="admin-secondary">Aperçu</button></div></section>
    <section className="admin-card"><h2 className="text-xl font-bold">Médias, récits et projets</h2><div className="grid md:grid-cols-2 gap-3 my-4"><input className="admin-input" placeholder="Identifiant unique" value={item.slug} onChange={(e) => setItem({...item, slug:e.target.value})}/><select className="admin-input" value={item.section} onChange={(e) => setItem({...item,section:e.target.value})}>{['home','agriculture','elevage','humanitaire'].map(x=><option key={x}>{x}</option>)}</select><input className="admin-input" placeholder="Titre" value={item.title} onChange={(e)=>setItem({...item,title:e.target.value})}/><input className="admin-input" placeholder="Badge" value={item.badge} onChange={(e)=>setItem({...item,badge:e.target.value})}/><textarea className="admin-input md:col-span-2" placeholder="Description" value={item.description} onChange={(e)=>setItem({...item,description:e.target.value})}/><textarea className="admin-input md:col-span-2" placeholder="Récit long" value={item.body} onChange={(e)=>setItem({...item,body:e.target.value})}/><input className="admin-input" placeholder="URL de l’image" value={item.imageUrl} onChange={(e)=>setItem({...item,imageUrl:e.target.value})}/><input className="admin-input" placeholder="Texte alternatif" value={item.imageAlt} onChange={(e)=>setItem({...item,imageAlt:e.target.value})}/><input className="admin-input" placeholder="Date affichée" value={item.dateLabel} onChange={(e)=>setItem({...item,dateLabel:e.target.value})}/><input className="admin-input" placeholder="Indicateur éditorial" value={item.metric} onChange={(e)=>setItem({...item,metric:e.target.value})}/><input className="admin-input" type="number" min="0" value={item.order} onChange={(e)=>setItem({...item,order:Number(e.target.value)})}/><label className="flex items-center gap-2"><input type="checkbox" checked={item.isActive} onChange={(e)=>setItem({...item,isActive:e.target.checked})}/> Visible</label></div><button disabled={busy} onClick={() => void saveMedia()} className="admin-primary">{item._id ? 'Mettre à jour' : 'Créer le média'}</button><div className="mt-5 divide-y">{media.map((entry)=><div key={entry._id} className="py-3 flex items-center justify-between gap-3"><div><strong className="text-sm">{entry.title}</strong><p className="text-xs text-gray-500">{entry.section} · ordre {entry.order} · {entry.isActive?'visible':'masqué'}</p></div><div className="flex gap-2"><button className="admin-secondary" onClick={()=>editMedia(entry)}>Modifier</button><button className="text-xs text-red-700" onClick={async()=>{if(entry._id){await contentApi.deleteMedia(entry._id);notify('Média supprimé');await load();}}}>Supprimer</button></div></div>)}</div></section></div>;
}
