import { useEffect, useMemo, useState } from 'react';
import { ContentBlock, ContentMap, contentApi, MediaItem } from '../../../services/contentApi';
import { MediaImageField } from './MediaImageField';
import { MediaList } from './MediaList';

type JsonValue = string | number | boolean | JsonObject | JsonValue[];
type JsonObject = { [key: string]: JsonValue };

const blockMeta: Record<keyof ContentMap, { group: string; label: string; preview: string; cards: Record<string, string> }> = {
  'home.page': { group: 'CONTENU', label: 'Accueil', preview: 'accueil', cards: { badge: 'En-tête / Hero', quote: 'Citation', metrics: 'Statistiques', storiesTitle: 'Reportages', projectsTitle: 'Chantiers participatifs', articlesEyebrow: 'Articles', upcomingTitle: "Bannière d’engagement" } },
  'agriculture.page': { group: 'CONTENU', label: 'Agriculture', preview: 'agriculture', cards: { header: 'En-tête / Hero', stats: 'Statistiques', storiesTitle: 'Reportages', guideCard: 'Guide agricole' } },
  'elevage.page': { group: 'CONTENU', label: 'Élevage', preview: 'elevage', cards: { header: 'En-tête / Hero', stats: 'Statistiques', storiesTitle: 'Reportages', adviceTitle: "Conseils de l’éleveur", ctaTitle: "Bannière d’engagement" } },
  'humanitaire.page': { group: 'CONTENU', label: 'Humanitaire', preview: 'humanitaire', cards: { header: 'En-tête / Hero', stats: 'Statistiques', chroniclesTitle: 'Récits', actionTitle: "Bannière d’engagement" } },
  'site.brand': { group: 'SITE', label: 'Identité du site', preview: 'accueil', cards: { name: 'Marque' } },
  'site.navigation': { group: 'SITE', label: 'Navigation', preview: 'accueil', cards: { items: 'Liens visibles', searchLabel: 'Actions du bandeau' } },
  'site.footer': { group: 'SITE', label: 'Pied de page', preview: 'accueil', cards: { description: 'Présentation', navigationTitle: 'Navigation', supportTitle: 'Engagement', copyright: 'Mentions' } },
  'site.contact': { group: 'SITE', label: 'Coordonnées', preview: 'humanitaire', cards: { location: 'Coordonnées publiques' } },
  'site.profile': { group: 'SITE', label: 'Profil / Biographie', preview: 'accueil', cards: { name: 'Identité', biography: 'Présentation', imageUrl: 'Portrait', buttonLabel: 'Appel à l’action' } },
  'site.search': { group: 'SITE', label: 'Recherche', preview: 'accueil', cards: { placeholder: 'Champ de recherche', suggestions: 'Suggestions', mediaTitle: 'Résultats et états vides' } },
  'site.guide': { group: 'SITE', label: 'Guide agricole', preview: 'agriculture', cards: { badge: 'Présentation du guide' } },
  'site.donation': { group: 'ENGAGEMENT', label: 'Dons', preview: 'humanitaire', cards: { badge: 'Présentation', projectLabel: 'Formulaire', categories: 'Projets proposés', suggestedAmounts: 'Montants suggérés', successBadge: 'Confirmation' } },
};

const labels: Record<string, string> = {
  badge: 'Badge', title: 'Titre', description: 'Description', primaryButton: 'Bouton principal', quote: 'Citation', quoteAuthor: 'Auteur', quoteCaption: 'Légende', metrics: 'Statistiques', header: 'En-tête', stats: 'Statistiques', name: 'Nom', subtitle: 'Sous-titre', logoUrl: 'URL du logo', logoAlt: 'Texte alternatif', buttonLabel: 'Libellé du bouton', introduction: 'Introduction', biography: 'Biographie', items: 'Liens de navigation', footerLabel: 'Libellé du pied de page', label: 'Libellé visible', categories: 'Catégories', suggestedAmounts: 'Montants suggérés', value: 'Valeur', id: 'Identifiant technique', icon: 'Icône technique', imageUrl: 'URL de l’image', imageAlt: 'Texte alternatif', order: 'Ordre', isActive: 'Visible', body: 'Contenu long', metric: 'Métrique', dateLabel: 'Date affichée', type: 'Type de contenu', section: 'Section', slug: 'Identifiant technique', metadata: 'Informations complémentaires', location: 'Lieu', category: 'Catégorie', duration: 'Durée', statusText: 'État affiché', expandedNarrative: 'Récit développé', impactBox: 'Encadré impact', searchLabel: 'Recherche', supportLabel: 'Bouton de soutien', profileLabel: 'Profil', upcomingEyebrow: 'Accroche', upcomingDescription: 'Description', upcomingPrimaryButton: 'Bouton principal', ctaTitle: 'Titre', ctaDescription: 'Description', donationButton: 'Bouton de don', contactButton: 'Bouton de contact', author: 'Auteur', emptyMessage: 'Message sans résultat', suggestions: 'Suggestions', placeholder: 'Texte indicatif', copyright: 'Droits d’auteur', signature: 'Signature', phone: 'Téléphone', email: 'E-mail', whatsapp: 'WhatsApp', sub: 'Précision', sublabel: 'Précision', color: 'Style visuel protégé', bg: 'Style visuel protégé', bgColor: 'Style visuel protégé', textColor: 'Style visuel protégé', tagIcon: 'Icône technique', badgeIcon: 'Icône technique', statsIcon: 'Icône technique', progress: 'Style de progression protégé', desc: 'Description', num: 'Numéro', readTime: 'Temps de lecture', actionText: 'Libellé d’action', btnText: 'Libellé d’action', statMetric: 'Métrique', statIcon: 'Icône technique', supportDescription: 'Description', profileButton: 'Bouton du profil', emptyArticlesTitle: 'Titre sans article', emptyArticlesDescription: 'Description sans article', articlesLoadingLabel: 'Message de chargement', articlesErrorLabel: 'Message d’erreur', retryLabel: 'Bouton réessayer',
};
const protectedLists = new Set(['items', 'categories']);
const technicalKeys = new Set(['id', 'value', 'icon', 'tagIcon', 'badgeIcon', 'statsIcon', 'progress', 'bg', 'bgColor', 'textColor', 'color', 'bgIcon']);
const urlKeys = /(?:url|image)$/i;
const longKeys = /description|biography|quote|text|introduction|narrative|message|copyright|note|body|desc/i;
const clone = <T,>(value: T): T => structuredClone(value);
const same = (a: unknown, b: unknown) => JSON.stringify(a) === JSON.stringify(b);
const emptyMedia: MediaItem = { slug: '', section: 'home', type: 'reportage', title: '', description: '', body: '', imageUrl: '', imageAlt: '', badge: '', dateLabel: '', metric: '', buttonLabel: '', metadata: {}, order: 0, isActive: true };

export function blankLike(value: JsonValue): JsonValue {
  if (Array.isArray(value)) return [];
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, key === 'isActive' ? true : blankLike(entry)]));
  if (typeof value === 'number') return 0;
  if (typeof value === 'boolean') return false;
  return '';
}

function Editor({ name, value, onChange, path = '' }: { name: string; value: JsonValue; onChange: (value: JsonValue) => void; path?: string }) {
  if (Array.isArray(value)) { const protectedList = protectedLists.has(name); return <div className="space-y-3">{value.map((entry, index) => <fieldset key={index} className="rounded-xl border border-gray-200 bg-gray-50 p-3"><legend className="px-2 text-xs font-bold text-gray-600">Élément {index + 1}</legend><Editor name="" value={entry} onChange={(next) => onChange(value.map((item, i) => i === index ? next : item))} path={`${path}.${index}`} /><div className="mt-3 flex flex-wrap gap-2"><button type="button" className="admin-secondary" disabled={index === 0} onClick={() => { const next = [...value]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; onChange(next); }}>Monter</button><button type="button" className="admin-secondary" disabled={index === value.length - 1} onClick={() => { const next = [...value]; [next[index + 1], next[index]] = [next[index], next[index + 1]]; onChange(next); }}>Descendre</button>{!protectedList && <button type="button" className="px-3 py-2 text-xs font-bold text-red-700" onClick={() => window.confirm('Supprimer cet élément ?') && onChange(value.filter((_, i) => i !== index))}>Supprimer</button>}</div></fieldset>)}{!protectedList && <button type="button" className="admin-secondary" onClick={() => onChange([...value, value.length ? blankLike(value[0]) : ''])}>Ajouter un élément</button>}</div>; }
  if (value && typeof value === 'object') return <div className="grid gap-4 md:grid-cols-2">{Object.entries(value).filter(([key]) => key !== 'videos').map(([key, entry]) => <Editor key={key} name={key} value={entry} onChange={(next) => onChange({ ...value, [key]: next })} path={`${path}.${key}`} />)}</div>;
  const readOnly = technicalKeys.has(name);
  const label = labels[name] || name.replace(/([A-Z])/g, ' $1').replace(/^./, (letter) => letter.toUpperCase());
  if (typeof value === 'boolean') return <label className="flex items-center gap-3 text-sm font-semibold"><input className="h-5 w-5" type="checkbox" checked={value} onChange={(event) => onChange(event.target.checked)} />{label}</label>;
  return <label className="block min-w-0 text-xs font-bold text-[#414844]">{label}{readOnly && <span className="ml-2 rounded bg-gray-200 px-2 py-0.5 font-normal">protégé</span>}{typeof value === 'number' ? <input className="admin-input mt-1" type="number" min={name === 'percent' ? 0 : undefined} max={name === 'percent' ? 100 : undefined} value={value} onChange={(event) => onChange(Number(event.target.value))} /> : longKeys.test(name) ? <textarea className="admin-input mt-1 min-h-28" maxLength={12000} value={value} readOnly={readOnly} onChange={(event) => onChange(event.target.value)} /> : <><input className={`admin-input mt-1 ${readOnly ? 'bg-gray-100 text-gray-500' : ''}`} type={urlKeys.test(name) ? 'url' : 'text'} maxLength={urlKeys.test(name) ? 2048 : 240} value={value} readOnly={readOnly} onChange={(event) => onChange(event.target.value)} />{urlKeys.test(name) && value && <img src={value} alt="Aperçu" className="mt-2 h-24 w-full rounded-lg bg-gray-100 object-cover" onError={(event) => { event.currentTarget.style.display = 'none'; }} />}</>}</label>;
}

function contentCards(data: JsonObject, meta: (typeof blockMeta)[keyof ContentMap]) {
  const entries = Object.entries(data); const starts = Object.keys(meta.cards);
  return starts.map((start, index) => ({ title: meta.cards[start], entries: entries.slice(entries.findIndex(([key]) => key === start), index + 1 < starts.length ? entries.findIndex(([key]) => key === starts[index + 1]) : entries.length) })).filter((card) => card.entries.length);
}

export function AdminContent({ notify }: { notify: (message: string) => void }) {
  const [blocks, setBlocks] = useState<ContentBlock[]>([]); const [media, setMedia] = useState<MediaItem[]>([]); const [selected, setSelected] = useState<keyof ContentMap>('home.page'); const [saved, setSaved] = useState<JsonObject>({}); const [draft, setDraft] = useState<JsonObject>({}); const [item, setItem] = useState<MediaItem>(emptyMedia); const [savedItem, setSavedItem] = useState<MediaItem>(emptyMedia); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const dirty = !same(saved, draft); const mediaDirty = !same(item, savedItem);
  const load = async (keepSelection = true) => { const payload = await contentApi.admin(); setBlocks(payload.blocks); setMedia(payload.mediaItems); const block = payload.blocks.find((entry) => entry.key === (keepSelection ? selected : 'home.page')) || payload.blocks[0]; if (block) { setSelected(block.key); setSaved(clone(block.data) as unknown as JsonObject); setDraft(clone(block.data) as unknown as JsonObject); } };
  useEffect(() => { void load(false).catch((reason) => setError(reason instanceof Error ? reason.message : 'Chargement impossible')); }, []);
  useEffect(() => { const beforeUnload = (event: BeforeUnloadEvent) => { if (dirty || mediaDirty) event.preventDefault(); }; window.addEventListener('beforeunload', beforeUnload); return () => window.removeEventListener('beforeunload', beforeUnload); }, [dirty, mediaDirty]);
  const confirmDiscard = () => !(dirty || mediaDirty) || window.confirm('Abandonner les modifications non enregistrées ?');
  const resetMedia = () => { setItem(clone(emptyMedia)); setSavedItem(clone(emptyMedia)); };
  const choose = (key: keyof ContentMap) => { if (!confirmDiscard()) return; const block = blocks.find((entry) => entry.key === key); if (block) { setSelected(key); setSaved(clone(block.data) as unknown as JsonObject); setDraft(clone(block.data) as unknown as JsonObject); resetMedia(); setError(''); } };
  const save = async () => { setBusy(true); setError(''); try { const result = await contentApi.update(selected, draft as unknown as ContentMap[typeof selected]); setSaved(clone(result.data) as unknown as JsonObject); setDraft(clone(result.data) as unknown as JsonObject); notify('Modifications enregistrées et publiées'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Échec de sauvegarde'); } finally { setBusy(false); } };
  const saveMedia = async () => { setBusy(true); setError(''); try { item.id ? await contentApi.updateMedia(item.id, item) : await contentApi.createMedia(item); notify('Média enregistré'); resetMedia(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Échec de sauvegarde du média'); } finally { setBusy(false); } };
  const editMedia = (entry: MediaItem) => { if (!confirmDiscard()) return; const next = clone({ ...emptyMedia, ...entry }); setItem(next); setSavedItem(clone(next)); document.querySelector('#media-editor')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
  const newMedia = () => { if (!confirmDiscard()) return; resetMedia(); document.querySelector('#media-editor')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
  const toggleMedia = async (entry: MediaItem) => { if (!entry.id) return; setBusy(true); setError(''); try { await contentApi.updateMedia(entry.id, { ...entry, isActive: !entry.isActive }); notify(entry.isActive ? 'Média masqué' : 'Média affiché'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Modification impossible'); } finally { setBusy(false); } };
  const deleteMedia = async (entry: MediaItem) => { if (!entry.id || !window.confirm(`Supprimer définitivement le média « ${entry.title} » ?`)) return; setBusy(true); setError(''); try { await contentApi.deleteMedia(entry.id); if (item.id === entry.id) resetMedia(); notify('Média supprimé'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Suppression impossible'); } finally { setBusy(false); } };
  const grouped = useMemo(() => ['CONTENU', 'SITE', 'ENGAGEMENT'].map((group) => ({ group, keys: (Object.keys(blockMeta) as (keyof ContentMap)[]).filter((key) => blockMeta[key].group === group && blocks.some((block) => block.key === key)) })), [blocks]);
  const meta = blockMeta[selected]; const cards = contentCards(draft, meta);
  return <div className="grid gap-6 xl:grid-cols-[250px_minmax(0,1fr)]"><aside className="admin-card h-fit xl:sticky xl:top-24"><h2 className="text-lg font-bold">Gestion du contenu</h2><p className="mt-1 text-xs text-gray-600">Les identifiants et styles techniques sont protégés.</p>{grouped.map(({ group, keys }) => <div key={group} className="mt-5"><h3 className="mb-2 text-[11px] font-black tracking-widest text-[#7d562d]">{group}</h3><div className="flex gap-2 overflow-x-auto xl:flex-col">{keys.map((key) => <button key={key} className={`whitespace-nowrap rounded-lg px-3 py-2 text-left text-sm ${selected === key ? 'bg-[#012d1d] font-bold text-white' : 'bg-gray-50 hover:bg-gray-100'}`} onClick={() => choose(key)}>{blockMeta[key].label}</button>)}</div></div>)}<div className="mt-5 border-t pt-4"><h3 className="mb-2 text-[11px] font-black tracking-widest text-[#7d562d]">MÉDIAS</h3><a href="#media" className="text-sm font-semibold">Reportages, récits et images</a></div></aside>
    <div className="min-w-0 space-y-6"><section><div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-xs font-bold text-[#7d562d]">{meta.group}</p><h2 className="text-2xl font-bold">{meta.label}</h2><p className="text-sm text-gray-600">{dirty ? 'Modifications non enregistrées' : 'Contenu à jour'}</p></div><div className="flex flex-wrap gap-2"><button className="admin-secondary" onClick={() => window.open(`/?tab=${meta.preview}`, '_blank', 'noopener,noreferrer')}>Aperçu de la page</button><button className="admin-secondary" disabled={!dirty || busy} onClick={() => setDraft(clone(saved))}>Annuler</button><button className="admin-primary" disabled={!dirty || busy} onClick={() => void save()}>{busy ? 'Enregistrement…' : 'Enregistrer'}</button></div></div>{error && <p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<div className="space-y-5">{cards.map((card) => <div className="admin-card" key={card.title}><h3 className="mb-4 text-lg font-bold text-[#012d1d]">{card.title}</h3><div className="grid gap-4 md:grid-cols-2">{card.entries.map(([key, value]) => <Editor key={key} name={key} value={value} path={`${selected}.${key}`} onChange={(next) => setDraft((current) => ({ ...current, [key]: next }))} />)}</div></div>)}</div></section>
      <section id="media" className="admin-card scroll-mt-24">
        <div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="text-xs font-bold text-[#7d562d]">MÉDIAS</p><h2 className="text-xl font-bold">Médias, récits et projets</h2><p className="text-sm text-gray-600">Gérez les reportages et publiez un type « Chantier / projet » pour le faire apparaître dans la section participative de l’accueil.</p></div><button type="button" className="admin-secondary h-fit" onClick={newMedia}>Nouveau média</button></div>
        <section id="media-editor" aria-labelledby="media-editor-title" className="mt-6 scroll-mt-24 rounded-xl bg-gray-50 p-4 sm:p-5">
          <h3 id="media-editor-title" className="text-lg font-bold">{item.id ? 'Modifier le média' : 'Créer un média'}</h3>
          {item.id && <p className="mt-2 text-xs text-gray-600">Identifiant technique : <code className="break-all rounded bg-gray-200 px-2 py-1">{item.slug}</code></p>}
          <div className="my-5 grid gap-4 md:grid-cols-2">
            <label className="text-xs font-bold">Section<select className="admin-input mt-1" value={item.section} onChange={(event) => setItem({ ...item, section: event.target.value as MediaItem['section'] })}>{(['home','agriculture','elevage','humanitaire'] as const).map((section) => <option key={section} value={section}>{blockMeta[`${section}.page` as keyof ContentMap]?.label || section}</option>)}</select></label>
            <label className="text-xs font-bold">Type<select className="admin-input mt-1" value={item.type} onChange={(event) => setItem({ ...item, type: event.target.value as MediaItem['type'] })}><option value="reportage">Reportage</option><option value="chronique">Chronique</option><option value="projet">Chantier / projet ouvert à la participation</option></select></label>
            {(['title','badge','description','body','dateLabel','metric','buttonLabel'] as const).map((key) => <Editor key={key} name={key} value={item[key] || ''} onChange={(value) => setItem({ ...item, [key]: String(value) })} />)}
            <MediaImageField url={item.imageUrl || ''} alt={item.imageAlt || ''} onUrlChange={(imageUrl) => setItem({ ...item, imageUrl })} onAltChange={(imageAlt) => setItem({ ...item, imageAlt })} />
            <Editor name="order" value={item.order} onChange={(value) => setItem({ ...item, order: Number(value) })} /><Editor name="isActive" value={item.isActive} onChange={(value) => setItem({ ...item, isActive: Boolean(value) })} />
            <div className="md:col-span-2"><h4 className="mb-3 text-sm font-bold">Informations complémentaires</h4><div className="grid gap-4 md:grid-cols-2">{(['duration','category','location','statusText','expandedNarrative','impactBox'] as const).map((key) => <Editor key={key} name={key} value={item.metadata[key] || ''} onChange={(value) => setItem({ ...item, metadata: { ...item.metadata, [key]: String(value) } })} />)}</div></div>
          </div>
          <div className="flex flex-wrap gap-2"><button type="button" className="admin-primary" disabled={busy || !item.title.trim() || !item.description.trim() || item.order < 0} onClick={() => void saveMedia()}>{busy ? 'Enregistrement…' : item.id ? 'Mettre à jour' : 'Créer le média'}</button><button type="button" className="admin-secondary" disabled={!mediaDirty || busy} onClick={() => setItem(clone(savedItem))}>Annuler les modifications</button></div>
        </section>
        <MediaList items={media} busy={busy} onEdit={editMedia} onToggle={(entry) => void toggleMedia(entry)} onDelete={(entry) => void deleteMedia(entry)} />
      </section>
    </div></div>;
}
