import { ConflictException, Injectable, NotFoundException } from '@nestjs/common'; import { ArticleStatus, Prisma } from '@prisma/client'; import slugify from 'slugify';
import { createHash } from 'crypto'; import { ConfigService } from '@nestjs/config'; import { PrismaService } from '../prisma/prisma.service'; import { ArticleQueryDto, CreateArticleDto, UpdateArticleDto } from './dto/article.dto';
@Injectable() export class ArticlesService {
 constructor(private prisma: PrismaService, private config: ConfigService) {}
 private async slug(title: string, exclude?: string) { const base = slugify(title, { lower: true, strict: true, locale: 'fr' }) || 'article'; let value=base, i=2; while(await this.prisma.article.findFirst({where:{slug:value,...(exclude?{id:{not:exclude}}:{})}})) value=`${base}-${i++}`; return value; }
 private include = { category: true } as const;
 async list(q: ArticleQueryDto, admin=false) { const where: Prisma.ArticleWhereInput={...(admin?{}:{status:'PUBLISHED'}),...(q.category?{category:{slug:q.category}}:{}),...(q.search?{OR:[{title:{contains:q.search,mode:'insensitive'}},{excerpt:{contains:q.search,mode:'insensitive'}}]}:{})}; const orderBy: Prisma.ArticleOrderByWithRelationInput=q.sort==='oldest'?{publishedAt:'asc'}:q.sort==='popular'?{viewsCount:'desc'}:{publishedAt:'desc'}; const [data,total]=await this.prisma.$transaction([this.prisma.article.findMany({where,include:this.include,orderBy,skip:(q.page-1)*q.limit,take:q.limit}),this.prisma.article.count({where})]); return {data,meta:{page:q.page,limit:q.limit,total,totalPages:Math.ceil(total/q.limit)}}; }
 async featured() { return this.prisma.article.findMany({where:{status:'PUBLISHED',isFeatured:true},include:this.include,orderBy:{publishedAt:'desc'}}); }
 async bySlug(slug:string) { const item=await this.prisma.article.findFirst({where:{slug,status:'PUBLISHED'},include:this.include}); if(!item) throw new NotFoundException('Article introuvable'); return item; }
 async create(dto:CreateArticleDto) { return this.prisma.article.create({data:{...dto,slug:await this.slug(dto.title),publishedAt:dto.status==='PUBLISHED'?new Date():null},include:this.include}); }
 async update(id:string,dto:UpdateArticleDto) { await this.require(id); const current=await this.prisma.article.findUniqueOrThrow({where:{id}}); return this.prisma.article.update({where:{id},data:{...dto,...(dto.title?{slug:await this.slug(dto.title,id)}:{}),...(dto.status?{publishedAt:dto.status==='PUBLISHED'?(current.publishedAt??new Date()):null}:{})},include:this.include}); }
 async remove(id:string) { await this.require(id); await this.prisma.article.delete({where:{id}}); return {success:true}; }
 status(id:string,status:ArticleStatus) { return this.update(id,{status}); }
 featuredStatus(id:string,isFeatured:boolean) { return this.update(id,{isFeatured}); }
 async view(id:string,identity:string) { const article=await this.prisma.article.findFirst({where:{id,status:'PUBLISHED'}}); if(!article) throw new NotFoundException('Article introuvable'); const bucket=new Date(); bucket.setUTCMinutes(0,0,0); const visitorHash=createHash('sha256').update(identity+this.config.getOrThrow('VIEW_HASH_SECRET')).digest('hex'); try { await this.prisma.$transaction([this.prisma.articleView.create({data:{articleId:id,visitorHash,bucket}}),this.prisma.article.update({where:{id},data:{viewsCount:{increment:1}}})]); return {counted:true}; } catch(e) { if(e instanceof Prisma.PrismaClientKnownRequestError && e.code==='P2002') return {counted:false}; throw e; } }
 private async require(id:string) { if(!await this.prisma.article.findUnique({where:{id},select:{id:true}})) throw new NotFoundException('Article introuvable'); }
}
